apiVersion: v1
data:
  logstash_rp_failure_elastic.conf: |+
     filter {
               if "VNFID" in [message] {
                #if "ERROR" in [message] or "CRITICAL" in [message] {
                
                  json {
                           source => "message"
                           remove_field => "timestamp_local"
                           remove_field => "message"
                             }
                        #Converting the time into UTC before sending into ELK
                 if [timezone] != "Z"{
                    date {
                     match => [ "timestamp", "ISO8601","MMM dd HH:mm:ss"]
                     timezone => "%{timezone}"
                     #timezone => "Etc/UTC"
                     target => "@timestamp"
                     remove_field => "timestamp"
                     }
                   }
                # Directly sending to ELK since time is in UTC
                else if [timezone] == "Z" {
                  date {
                    match => [ "timestamp", "ISO8601","MMM dd HH:mm:ss"]
                    target => "@timestamp"
                    remove_field => "timestamp"
                   }
                 }
                 

                        grok {
                            match => {"log" => "%{NOTSPACE}\s%{WORD:app_name}\:\s%{USERNAME:log_level}\,%{NOTSPACE}\,%{NOTSPACE:sub_module}\,%{GREEDYDATA:log_message}"}
                            #add_field => { "log_type" => "rp-debug"}
                            remove_field => "log" 
                             }
                        if "_grokparsefailure" in [tags] {
                            grok {
                               match => {"log" => "%{NOTSPACE}\s%{NOTSPACE}\s%{WORD:app_name}\[%{NOTSPACE}\]\:\s%{USERNAME:log_level}\,%{NOTSPACE}\,%{NOTSPACE:sub_module}\,%{GREEDYDATA:log_message}"}
                               remove_field => "log"
                               remove_field => "tags" 
                               #add_field => { "log_type" => "rp-debug"}
                               }}
                        if [log_level] == "ERROR" or [log_level] == "CRITICAL"  {
                            mutate
                                add_field => { "log_type" => "rp-debug"} }
                     
                       if "rp-debug" not in [log_type]{
                           grok {
                              match => {"log"=> "%{GREEDYDATA:log_message}"}
                              remove_field => "log"
                              add_field => {"log_type" => "rp-debug-unknown"}
                                }
                              }
                 } 
               }
               
kind: ConfigMap
metadata:
  name: logstash-pipeline-rp-failure-event-elasticsearch-test
  namespace: default
  labels:
    app: "{{ template "logstash.fullname" . }}"
    chart: "{{ .Chart.Name }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
